name: Tests
on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: snok/install-poetry@v1.3.4
      - name: install dependencies
        run: poetry install
      - name: Black formatter
        run: poetry run black --check .
      - name: Flake linter
        run: poetry run flake8 .
      - name: isort
        run: poetry run isort --profile black --check .
      - name: tests
        run: poetry run pytest --tavern-http-backend=flask --cov tavern_flask example
